# Generated by Django 5.1.5 on 2025-02-04 14:16

import movie.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=movie.storage_backends.AzureMediaStorage(), upload_to='videos/'),
        ),
    ]
